[tool.poetry]
name = "adventofcode2020"
version = "0.1.0"
description = ""
authors = ["virunus <tech+git@virunus.com>"]

[tool.poetry.dependencies]
python = "^3.8.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
